-- MySQL Script generated by MySQL Workbench
-- dom 29 nov 2015 16:56:48 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema u919364308_daw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema u919364308_daw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u919364308_daw` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `u919364308_daw` ;

-- -----------------------------------------------------
-- Table `u919364308_daw`.`descuentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u919364308_daw`.`descuentos` (
  `iddescuento` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fechainicio` DATE NULL COMMENT '',
  `fechafin` DATE NULL COMMENT '',
  `porcentaje` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`iddescuento`)  COMMENT '')
;


-- -----------------------------------------------------
-- Table `u919364308_daw`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u919364308_daw`.`productos` (
  `idproducto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `titulo` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `precio` DECIMAL NULL COMMENT '',
  `gatosdeenvio` DECIMAL NULL COMMENT '',
  `marca` VARCHAR(45) NULL COMMENT '',
  `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `iddescuento` INT NULL COMMENT '',
  PRIMARY KEY (`idproducto`)  COMMENT '',
  INDEX `fk_productos_descuentos1_idx` (`iddescuento` ASC)  COMMENT '')
;


-- -----------------------------------------------------
-- Table `u919364308_daw`.`metodosPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u919364308_daw`.`metodosPago` (
  `idmetodo` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idmetodo`)  COMMENT '')
;


-- -----------------------------------------------------
-- Table `u919364308_daw`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u919364308_daw`.`usuarios` (
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellidos` VARCHAR(45) NULL COMMENT '',
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `telefono` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `direccion` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `orden` TINYINT(1) NULL DEFAULT 1 COMMENT '',
  `rol` VARCHAR(45) NULL DEFAULT 'cliente' COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `public` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`username`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '')
;


-- -----------------------------------------------------
-- Table `u919364308_daw`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u919364308_daw`.`compras` (
  `idcompra` INT NOT NULL COMMENT '',
  `idmetodo` VARCHAR(45) NULL COMMENT '',
  `hash_compra` VARCHAR(45) NOT NULL COMMENT '',
  `estado` VARCHAR(20) NULL COMMENT '',
  `fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idcompra`, `username`)  COMMENT '',
  INDEX `fk_compras_metodosPago1_idx` (`idmetodo` ASC)  COMMENT '',
  UNIQUE INDEX `hash_compra_UNIQUE` (`hash_compra` ASC)  COMMENT '',
  INDEX `fk_compras_usuarios1_idx` (`username` ASC)  COMMENT '')
;


-- -----------------------------------------------------
-- Table `u919364308_daw`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u919364308_daw`.`categorias` (
  `idcategoria` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idcategoria`)  COMMENT '')
;


-- -----------------------------------------------------
-- Table `u919364308_daw`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u919364308_daw`.`imagenes` (
  `idimagen` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `path` LONGTEXT NULL COMMENT '',
  `idproducto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idimagen`)  COMMENT '',
  INDEX `fk_imagenes_productos1_idx` (`idproducto` ASC)  COMMENT '')
;


-- -----------------------------------------------------
-- Table `u919364308_daw`.`caracteristicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u919364308_daw`.`caracteristicas` (
  `color` VARCHAR(10) NOT NULL COMMENT '',
  `talla` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`color`, `talla`)  COMMENT '')
;


-- -----------------------------------------------------
-- Table `u919364308_daw`.`subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u919364308_daw`.`subcategorias` (
  `idsubcategoria` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idsubcategoria`)  COMMENT '')
;


-- -----------------------------------------------------
-- Table `u919364308_daw`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u919364308_daw`.`color` (
  `idcolor` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idcolor`)  COMMENT '')
;


-- -----------------------------------------------------
-- Table `u919364308_daw`.`tallas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u919364308_daw`.`tallas` (
  `idtalla` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idtalla`)  COMMENT '')
;


-- -----------------------------------------------------
-- Table `u919364308_daw`.`tallas_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u919364308_daw`.`tallas_color` (
  `idtalla` VARCHAR(45) NOT NULL COMMENT '',
  `idcolor` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idtalla`, `idcolor`)  COMMENT '',
  INDEX `fk_tallas_has_color_color1_idx` (`idcolor` ASC)  COMMENT '',
  INDEX `fk_tallas_has_color_tallas1_idx` (`idtalla` ASC)  COMMENT '')
;


-- -----------------------------------------------------
-- Table `u919364308_daw`.`productos_tallas_colores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u919364308_daw`.`productos_tallas_colores` (
  `idproducto` INT NOT NULL COMMENT '',
  `idtalla` VARCHAR(45) NOT NULL COMMENT '',
  `idcolor` VARCHAR(45) NOT NULL COMMENT '',
  `stock` DECIMAL NULL COMMENT '',
  PRIMARY KEY (`idproducto`, `idtalla`, `idcolor`)  COMMENT '',
  INDEX `fk_productos_has_tallas_color_tallas_color1_idx` (`idtalla` ASC, `idcolor` ASC)  COMMENT '',
  INDEX `fk_productos_has_tallas_color_productos1_idx` (`idproducto` ASC)  COMMENT '')
;


-- -----------------------------------------------------
-- Table `u919364308_daw`.`compras_productos_tallas_colores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u919364308_daw`.`compras_productos_tallas_colores` (
  `idcompra` INT NOT NULL COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `idproducto` INT NOT NULL COMMENT '',
  `idtalla` VARCHAR(45) NOT NULL COMMENT '',
  `idcolor` VARCHAR(45) NOT NULL COMMENT '',
  `cantidad` INT NULL COMMENT '',
  PRIMARY KEY (`idcompra`, `username`, `idproducto`, `idtalla`, `idcolor`)  COMMENT '',
  INDEX `fk_compras_has_productos_tallas_colores_productos_tallas_co_idx` (`idproducto` ASC, `idtalla` ASC, `idcolor` ASC)  COMMENT '',
  INDEX `fk_compras_has_productos_tallas_colores_compras1_idx` (`idcompra` ASC, `username` ASC)  COMMENT '')
;


-- -----------------------------------------------------
-- Table `u919364308_daw`.`subcategorias_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u919364308_daw`.`subcategorias_categorias` (
  `idsubcategoria` VARCHAR(45) NOT NULL COMMENT '',
  `idcategoria` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idsubcategoria`, `idcategoria`)  COMMENT '',
  INDEX `fk_subcategorias_has_categorias_categorias1_idx` (`idcategoria` ASC)  COMMENT '',
  INDEX `fk_subcategorias_has_categorias_subcategorias1_idx` (`idsubcategoria` ASC)  COMMENT '')
;


-- -----------------------------------------------------
-- Table `u919364308_daw`.`productos_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u919364308_daw`.`productos_categorias` (
  `idproducto` INT NOT NULL COMMENT '',
  `idcategoria` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idproducto`, `idcategoria`)  COMMENT '',
  INDEX `fk_productos_has_categorias_categorias1_idx` (`idcategoria` ASC)  COMMENT '',
  INDEX `fk_productos_has_categorias_productos1_idx` (`idproducto` ASC)  COMMENT '')
;

insert into u919364308_daw.usuarios values('test', 'test', 'test', '2015-11-27 00:56:09', 'test@gmail.com', NULL, NULL, '1', 'administrador', '56a/NpXpEac4I', 0);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
